version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest

volumes:
  postgres_data:

networks:
  nest:
